### ISSUE TITLE
__str__ for debug

### ISSUE THREAD

**Issue by hibit-at** [Schippi/py-bsor#1]
thank you for this library, I am now studying about this.
I think the classes need __str__ expression because it helps debugging a lot.
Or, would I implement it and send a pull-request?
![image](https://user-images.githubusercontent.com/43929933/223394891-1b26ed88-48b9-4944-a922-358664f7e91c.png)

**Comment by Schippi** [comment]
i released a new version that has some more human readable __str__
0.9.11
