### ISSUE TITLE
Encoding a bsor with a miss fails

### ISSUE THREAD

**Issue by atch2203** [Schippi/py-bsor#7]
Line 323 in Bsor.py attempts to write Note.cut, but Note objects that are misses don't have the self.cut attribute.

Code to replicate:

```python
with open('replay_with_a_miss.bsor', "rb") as f:
        m = make_bsor(f)
        with open('out.bsor', 'wb') as out:
            m.write(out)
```

Scuffed fix (would not recommend)

```python
def write(self, f: BinaryIO):
    if not hasattr(self, 'cut'): self.cut = None
    write_things(f, [self.note_id, self.event_time, self.spawn_time, self.event_type, self.cut])
```

Also while I'm here the magic_number attribute of Bsor is misspelled

**Comment by Schippi** [comment]
thanks, updated in 1.2.3
